// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LEORE.Models;

public partial class CartItem
{
    [Key]
    public int CartItemsId { get; set; }

    public int ProductID { get; set; }

    public int Quantity { get; set; }

    public int? CartId { get; set; }

    [ForeignKey("CartId")]
    [InverseProperty("CartItems")]
    public virtual Cart Cart { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("CartItems")]
    public virtual Product Product { get; set; }
}