// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LEORE.Models;

public partial class OrderItem
{
    [Key]
    public int OrderItemID { get; set; }

    public int ProductID { get; set; }

    public int OrderId { get; set; }

    [Column(TypeName = "decimal(9, 2)")]
    public decimal PriceAtPurchase { get; set; }

    public int Quantity { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("OrderItems")]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("OrderItems")]
    public virtual Product Product { get; set; }
}