// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LEORE.Models;

public partial class ProductReview
{
    [Key]
    public int ReviewID { get; set; }

    public int ProductID { get; set; }

    public int UserID { get; set; }

    [Required]
    public string Comment { get; set; }

    public int Rating { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("ProductReviews")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("ProductReviews")]
    public virtual User User { get; set; }
}