// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LEORE.Models;

public partial class RefreshToken
{
    [Key]
    public int RefreshTokensID { get; set; }

    [Required]
    [StringLength(500)]
    public string Token { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ExpiresOn { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? RevokedOn { get; set; }

    public bool IsActive { get; set; }

    public int UserID { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("RefreshTokens")]
    public virtual User User { get; set; }
}