// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LEORE.Models;

public partial class WishList
{
    [Key]
    public int WishlistID { get; set; }

    public int UserID { get; set; }

    [ForeignKey("UserID")]
    [InverseProperty("WishLists")]
    public virtual User User { get; set; }

    [InverseProperty("Wishlist")]
    public virtual ICollection<WishListItem> WishListItems { get; set; } = new List<WishListItem>();
}