// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LEORE.Models;

public partial class WishListItem
{
    [Key]
    public int WishlistItemsId { get; set; }

    public int WishlistID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime AddedAt { get; set; }

    public int ProductID { get; set; }

    [ForeignKey("ProductID")]
    [InverseProperty("WishListItems")]
    public virtual Product Product { get; set; }

    [ForeignKey("WishlistID")]
    [InverseProperty("WishListItems")]
    public virtual WishList Wishlist { get; set; }
}